language: java
jdk:
  - openjdk12
env:
  - DSTAMP=$(date +%F)
addons:
  apt:
    packages:
      - ant-optional
before_install:
  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_EVENT_TYPE" == "cron" ]]; then .travis/merge-sourceforge.sh; fi
  - if [[ "$TRAVIS_BRANCH" == "slim" && "$TRAVIS_EVENT_TYPE" == "cron" ]]; then .travis/merge-slim.sh; fi
  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_EVENT_TYPE" == "cron" ]]; then .travis/deploy-sourceforge-merge.sh; fi
  - if [[ "$TRAVIS_BRANCH" == "slim" && "$TRAVIS_EVENT_TYPE" == "cron" ]]; then .travis/deploy-slim-merge.sh; fi
script:
  - ant testci
before_deploy:
  - ant nightly-release
  - ls -l dist/releases
deploy:
  provider: releases
  skip_cleanup: true
  tag_name: "nightly-$DSTAMP"
  prerelease: true
  name: "Nightly Release: $DSTAMP"
  token: $GITHUB_TOKEN
  file_glob: true
  file: "dist/releases/*"
